import Navbar from "@/components/Navbar"
import "./globals.css"
import { AuthProvider } from "@/contexts/authContext"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <Navbar />
          <main className="p-6">{children}</main>
        </body>
      </AuthProvider>
    </html>
  )
}
